version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress-network
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wp
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-network
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8443:443"
    networks:
      - wordpress-network
    restart: always

networks:
  wordpress-network:

volumes:
  mariadb_data:
  wordpress_data:
