version: '3'

services:
  mariadb:
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress-network
    restart: always

  wordpress:
    depends_on:
      - mariadb
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-network
    restart: always

  nginx:
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - wordpress-network
    restart: always

networks:
  wordpress-network:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rel-sima/data/db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rel-sima/data/wordpress