FROM debian:bullseye

WORKDIR /var/www/html

RUN apt-get update && apt-get install --no-install-recommends -y \
  php7.4-fpm \
  php7.4-cli \
  ca-certificates \
  mariadb-client curl \
  php php-bcmath php-curl php-imagick php-intl \
  php-json php-mbstring php-mysql php-xml php-zip \
  && rm -rf /var/lib/apt/lists/*

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY tools/installing_wp_cli.sh /usr/local/bin/installing_wp_cli.sh
COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN mkdir /run/php

ENTRYPOINT ["bash", "/usr/local/bin/installing_wp_cli.sh"]
CMD ["php-fpm7.4", "-F"]
