# Use the Debian bullseye base image
FROM debian:bullseye

# Add metadata to the image for description and maintainer
LABEL description="Nginx Docker image"
LABEL maintainer="rachid el-ismaiyly <relismaiyly@gmail.com>"

# Update the package list and install Nginx and OpenSSL without recommended packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    nginx \
    openssl

# Copy the SSL generation script into the container's /usr/local/bin directory
COPY tools/generate_ssl.sh /usr/local/bin/generate_ssl.sh

RUN chmod +x /usr/local/bin/generate_ssl.sh

RUN /usr/local/bin/generate_ssl.sh

# Remove default server configuration files
RUN rm /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Copy the custom Nginx configuration into the container
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 443 to allow HTTPS connections
EXPOSE 443


# Start Nginx in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]
